# Nettoyage des données

## Objectif
Préparer le dataset pour le feature engineering et l’entraînement du modèle. 
- Convertir `date_time` en datetime
- Créer des colonnes temporelles utiles
- Traiter les valeurs manquantes
- Vérifier types et incohérences

## 1. Import des librairies

In [1]:
import pandas as pd
import numpy as np

## 2. Chargement des données

In [2]:
df = pd.read_csv("../data/raw/Metro_Interstate_Traffic_Volume.csv")
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

## 3. Conversion de date_time en datetime

In [3]:

df['date_time'] = pd.to_datetime(df['date_time'])

## 4. Création de colonnes temporelles

In [4]:
df['hour'] = df['date_time'].dt.hour
df['day'] = df['date_time'].dt.day
df['month'] = df['date_time'].dt.month
df['weekday'] = df['date_time'].dt.weekday
df['is_weekend'] = df['weekday'].apply(lambda x: 1 if x >= 5 else 0)


df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,hour,day,month,weekday,is_weekend
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545,9,2,10,1,0
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516,10,2,10,1,0
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767,11,2,10,1,0
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026,12,2,10,1,0
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918,13,2,10,1,0

## 5. Vérification des valeurs manquantes

In [5]:
df = df[df['traffic_volume'] >= 0].copy()
df.fillna(method='ffill', inplace=True)

/tmp/ipykernel_313395/4233375200.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

## 6. Vérification des incohérences

In [6]:

(df['traffic_volume'] < 0).sum()

np.int64(0)

## 7. Sauvegarde des données nettoyées

In [7]:
df.to_csv("../data/processed/traffic_cleaned.csv", index=False)

## Conclusion

- `date_time` converti en datetime
- Nouvelles colonnes temporelles créées : hour, day, month, weekday, is_weekend
- Valeurs manquantes traitées
- Dataset prêt pour le feature engineering